apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - configmap.yaml
images:
  - name: svelte-frontend
patches:
  - path: resource_patch.json
    target:
      kind: Deployment
      name: svelte-frontend
